// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 向前端暴露配置的读取与保存能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Defaults 返回内置默认配置，供「恢复默认」使用。
 */
export function Defaults(): $CancellablePromise<$models.ConfigDTO> {
    return $Call.ByID(3928131381);
}

/**
 * Get 读取当前配置（附带配置文件所在路径，便于界面展示）。
 * 读取失败时仍然返回默认配置，让界面可用。
 */
export function Get(): $CancellablePromise<$models.ConfigDTO> {
    return $Call.ByID(143529565);
}

/**
 * Save 校验并写入配置。任一项不合法时返回错误，不落盘。
 */
export function Save(latency: number, concurrency: number, timeout: number, $number: number): $CancellablePromise<void> {
    return $Call.ByID(2730444782, latency, concurrency, timeout, $number);
}
