// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IPService 提供 IP 来源相关能力：内置网段、导入文件、解析、剪贴板。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuiltinCIDRs 返回内置网段：优先在线拉取官方列表，拉取失败时回退到编译期内置列表。
 * @returns {$CancellablePromise<$models.CIDRSource>}
 */
export function BuiltinCIDRs() {
    return $Call.ByID(1272474878).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BuiltinText 返回指定网段的文本，每行一条；sample <= 0 时不指定采样数。
 * cidrs 为空时返回全部内置网段。
 * @param {string[]} cidrs
 * @param {number} sample
 * @returns {$CancellablePromise<string>}
 */
export function BuiltinText(cidrs, sample) {
    return $Call.ByID(2533083696, cidrs, sample);
}

/**
 * CopyToClipboard 把文本写入系统剪贴板。
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function CopyToClipboard(text) {
    return $Call.ByID(2098103826, text);
}

/**
 * ImportFile 打开系统文件对话框选择 ip.txt 并读取内容。
 * @returns {$CancellablePromise<$models.ImportResult>}
 */
export function ImportFile() {
    return $Call.ByID(2542830051).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Parse 解析 IP 文本，返回可测速的 IP 数量，供前端实时校验输入。
 * @param {string} text
 * @returns {$CancellablePromise<number>}
 */
export function Parse(text) {
    return $Call.ByID(2825038871, text);
}

// Private type creation functions
const $$createType0 = $models.CIDRSource.createFrom;
const $$createType1 = $models.ImportResult.createFrom;
