// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IPService 提供 IP 来源相关能力：内置网段、导入文件、解析、剪贴板。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuiltinCIDRs 返回内置网段：优先在线拉取官方列表，拉取失败时回退到编译期内置列表。
 */
export function BuiltinCIDRs(): $CancellablePromise<$models.CIDRSource> {
    return $Call.ByID(1272474878);
}

/**
 * BuiltinText 返回指定网段的文本，每行一条；sample <= 0 时不指定采样数。
 * cidrs 为空时返回全部内置网段。
 */
export function BuiltinText(cidrs: string[] | null, sample: number): $CancellablePromise<string> {
    return $Call.ByID(2533083696, cidrs, sample);
}

/**
 * CopyToClipboard 把文本写入系统剪贴板。
 */
export function CopyToClipboard(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(2098103826, text);
}

/**
 * ImportFile 打开系统文件对话框选择 ip.txt 并读取内容。
 */
export function ImportFile(): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(2542830051);
}

/**
 * Parse 解析 IP 文本，返回可测速的 IP 数量，供前端实时校验输入。
 */
export function Parse(text: string): $CancellablePromise<number> {
    return $Call.ByID(2825038871, text);
}
