// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 提供日志目录访问、导出与打开能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Dir 返回日志目录路径
 */
export function Dir(): $CancellablePromise<string> {
    return $Call.ByID(373861214);
}

/**
 * Export 弹出系统保存对话框，把内容写入用户指定的文件，返回实际路径。
 */
export function Export(content: string, filename: string): $CancellablePromise<string> {
    return $Call.ByID(2560179949, content, filename);
}

/**
 * OpenDir 用系统文件管理器打开日志目录
 */
export function OpenDir(): $CancellablePromise<void> {
    return $Call.ByID(2249375522);
}
