// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CIDRSource 内置网段列表及其来源，便于界面告知用户用的是在线还是内置。
 */
export interface CIDRSource {
    "CIDRs": string[] | null;

    /**
     * true = 在线拉取成功
     */
    "Online": boolean;

    /**
     * 在线拉取失败的原因，仅 Online 为 false 时有值
     */
    "Error": string;
}

/**
 * ColoOption 内置推荐的机房，供界面快捷选择。
 */
export interface ColoOption {
    /**
     * IATA 三字码
     */
    "Code": string;

    /**
     * 中文名
     */
    "Name": string;
}

/**
 * ConfigDTO 是给前端用的配置视图，字段与 config.Config 一一对应。
 * Path 只读，Save 会忽略它。
 */
export interface ConfigDTO {
    "Latency": number;
    "Concurrency": number;
    "Timeout": number;
    "Number": number;
    "Colo": string;
    "PrimarySize": number;
    "BackupSize": number;
    "Cooldown": number;
    "HealthInterval": number;
    "PingTimes": number;
    "PingGap": number;
    "LossLimit": number;
    "ProxyListen": string;
    "Path": string;
}

/**
 * EvictionRecord 一条淘汰记录
 */
export interface EvictionRecord {
    "IP": string;
    "Reason": string;

    /**
     * Unix 毫秒
     */
    "Time": number;
}

/**
 * ImportResult 导入 ip.txt 的结果。
 */
export interface ImportResult {
    /**
     * 文件完整路径
     */
    "Path": string;

    /**
     * 文件内容，前端据此回填到输入框
     */
    "Content": string;

    /**
     * 解析出的 IP 数量
     */
    "Count": number;
}

/**
 * PoolNode 池中的一个节点视图。Latency 单位为毫秒，取最近一轮采样结果。
 */
export interface PoolNode {
    "IP": string;
    "Colo": string;

    /**
     * 最近一轮采样的均值；该轮全失败时保留上一次的值
     */
    "Latency": number;
    "LossRate": number;
    "Samples": number;
    "FailStreak": number;
    "Isolated": boolean;

    /**
     * Unix 毫秒
     */
    "UpdatedAt": number;
}

/**
 * PoolSnapshot 池的完整快照，前端据此整体刷新界面
 */
export interface PoolSnapshot {
    "Running": boolean;
    "Phase": string;

    /**
     * 候选 IP 总数
     */
    "ScanTotal": number;

    /**
     * 本轮扫描已探测的数量
     */
    "ScanDone": number;
    "PrimaryTarget": number;
    "BackupTarget": number;

    /**
     * 本地 SOCKS5 监听地址；空串表示未监听
     */
    "ListenAddr": string;
    "ListenError": string;
    "ActiveConns": number;

    /**
     * 最近一次成功转发的节点，供界面高亮
     */
    "LastUsedIP": string;

    /**
     * Unix 毫秒
     */
    "LastUsedAt": number;
    "Primary": PoolNode[] | null;
    "Backup": PoolNode[] | null;
    "Evictions": EvictionRecord[] | null;
}

/**
 * SpeedResult 单条测速结果。Latency 单位为毫秒，小于 0 表示请求失败。
 */
export interface SpeedResult {
    /**
     * 自增序号，前端用它做 :key
     */
    "Seq": number;
    "IP": string;
    "Latency": number;
    "Source": string;

    /**
     * 机房代码，取自 cf-ray；可能为空
     */
    "Colo": string;

    /**
     * 是否通过机房白名单，前端据此标记「机房不符」
     */
    "Allowed": boolean;
}

/**
 * SpeedSummary 一次测速结束后的汇总。
 */
export interface SpeedSummary {
    /**
     * 已探测数量
     */
    "Total": number;

    /**
     * 达标：机房通过白名单、探测成功且延迟不超过上限
     */
    "Qualified": number;

    /**
     * 超标：探测成功但延迟超过上限
     */
    "OverLimit": number;

    /**
     * 请求失败
     */
    "Failed": number;

    /**
     * 机房不符：未通过白名单
     */
    "Excluded": number;

    /**
     * 耗时（毫秒）
     */
    "Elapsed": number;

    /**
     * true = 提前结束（集满或手动停止）
     */
    "Stopped": boolean;
    "LogPath": string;
}
