// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CIDRSource 内置网段列表及其来源，便于界面告知用户用的是在线还是内置。
 */
export class CIDRSource {
    /**
     * Creates a new CIDRSource instance.
     * @param {Partial<CIDRSource>} [$$source = {}] - The source object to create the CIDRSource.
     */
    constructor($$source = {}) {
        if (!("CIDRs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["CIDRs"] = [];
        }
        if (!("Online" in $$source)) {
            /**
             * true = 在线拉取成功
             * @member
             * @type {boolean}
             */
            this["Online"] = false;
        }
        if (!("Error" in $$source)) {
            /**
             * 在线拉取失败的原因，仅 Online 为 false 时有值
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CIDRSource instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CIDRSource}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CIDRs" in $$parsedSource) {
            $$parsedSource["CIDRs"] = $$createField0_0($$parsedSource["CIDRs"]);
        }
        return new CIDRSource(/** @type {Partial<CIDRSource>} */($$parsedSource));
    }
}

/**
 * ConfigDTO 是给前端用的配置视图，字段与 config.Config 一一对应。
 */
export class ConfigDTO {
    /**
     * Creates a new ConfigDTO instance.
     * @param {Partial<ConfigDTO>} [$$source = {}] - The source object to create the ConfigDTO.
     */
    constructor($$source = {}) {
        if (!("Latency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Latency"] = 0;
        }
        if (!("Concurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Concurrency"] = 0;
        }
        if (!("Timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Timeout"] = 0;
        }
        if (!("Number" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Number"] = 0;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigDTO(/** @type {Partial<ConfigDTO>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入 ip.txt 的结果。
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("Path" in $$source)) {
            /**
             * 文件完整路径
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * 文件内容，前端据此回填到输入框
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }
        if (!("Count" in $$source)) {
            /**
             * 解析出的 IP 数量
             * @member
             * @type {number}
             */
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * SpeedResult 单条测速结果。Latency 单位为毫秒，小于 0 表示失败。
 */
export class SpeedResult {
    /**
     * Creates a new SpeedResult instance.
     * @param {Partial<SpeedResult>} [$$source = {}] - The source object to create the SpeedResult.
     */
    constructor($$source = {}) {
        if (!("Seq" in $$source)) {
            /**
             * 自增序号，前端用它做 :key
             * @member
             * @type {number}
             */
            this["Seq"] = 0;
        }
        if (!("IP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IP"] = "";
        }
        if (!("Latency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Latency"] = 0;
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeedResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpeedResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpeedResult(/** @type {Partial<SpeedResult>} */($$parsedSource));
    }
}

/**
 * SpeedSummary 一次测速结束后的汇总。
 */
export class SpeedSummary {
    /**
     * Creates a new SpeedSummary instance.
     * @param {Partial<SpeedSummary>} [$$source = {}] - The source object to create the SpeedSummary.
     */
    constructor($$source = {}) {
        if (!("Total" in $$source)) {
            /**
             * 已探测数量
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("Success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Success"] = 0;
        }
        if (!("Failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Failed"] = 0;
        }
        if (!("Elapsed" in $$source)) {
            /**
             * 耗时（毫秒）
             * @member
             * @type {number}
             */
            this["Elapsed"] = 0;
        }
        if (!("Stopped" in $$source)) {
            /**
             * true = 提前结束（集满或手动停止），false = 全部跑完
             * @member
             * @type {boolean}
             */
            this["Stopped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeedSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpeedSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpeedSummary(/** @type {Partial<SpeedSummary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
