// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CIDRSource 内置网段列表及其来源，便于界面告知用户用的是在线还是内置。
 */
export interface CIDRSource {
    "CIDRs": string[] | null;

    /**
     * true = 在线拉取成功
     */
    "Online": boolean;

    /**
     * 在线拉取失败的原因，仅 Online 为 false 时有值
     */
    "Error": string;
}

/**
 * ConfigDTO 是给前端用的配置视图，字段与 config.Config 一一对应。
 */
export interface ConfigDTO {
    "Latency": number;
    "Concurrency": number;
    "Timeout": number;
    "Number": number;
    "Path": string;
}

/**
 * ImportResult 导入 ip.txt 的结果。
 */
export interface ImportResult {
    /**
     * 文件完整路径
     */
    "Path": string;

    /**
     * 文件内容，前端据此回填到输入框
     */
    "Content": string;

    /**
     * 解析出的 IP 数量
     */
    "Count": number;
}

/**
 * SpeedResult 单条测速结果。Latency 单位为毫秒，小于 0 表示请求失败。
 */
export interface SpeedResult {
    /**
     * 自增序号，前端用它做 :key
     */
    "Seq": number;
    "IP": string;
    "Latency": number;
    "Source": string;
}

/**
 * SpeedSummary 一次测速结束后的汇总。
 */
export interface SpeedSummary {
    /**
     * 已探测数量
     */
    "Total": number;

    /**
     * 达标：探测成功且延迟不超过上限
     */
    "Qualified": number;

    /**
     * 超标：探测成功但延迟超过上限
     */
    "OverLimit": number;

    /**
     * 请求失败
     */
    "Failed": number;

    /**
     * 耗时（毫秒）
     */
    "Elapsed": number;

    /**
     * true = 提前结束（集满或手动停止）
     */
    "Stopped": boolean;
    "LogPath": string;
}
