// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService 构建并长期维护 IP 池，并在池有节点后开启本地 SOCKS5 转发。
 * 与 SpeedService（一次性测速）相互独立。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Snapshot 返回当前池的快照
 */
export function Snapshot(): $CancellablePromise<$models.PoolSnapshot> {
    return $Call.ByID(2784978769);
}

/**
 * StartPool 扫描达标节点填满池，随后开启 SOCKS5 转发与周期健康检查。
 */
export function StartPool(text: string): $CancellablePromise<void> {
    return $Call.ByID(2205807473, text);
}

/**
 * StopPool 停止扫描、转发与健康检查，池中节点保留以便查看。
 */
export function StopPool(): $CancellablePromise<void> {
    return $Call.ByID(1860328887);
}
