// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeedService 负责流式测速，结果通过事件逐条推给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * IsRunning 报告测速是否正在进行。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning() {
    return $Call.ByID(3540933809);
}

/**
 * Start 解析 IP 文本并开始测速。已在测速时返回错误。
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Start(text) {
    return $Call.ByID(1210520814, text);
}

/**
 * Stop 手动停止测速。
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(171725110);
}
