// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SpeedService 负责流式测速，结果通过事件逐条推给前端。
 * 停止条件：达标数量达到 cfg.Number。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IsRunning 报告测速是否正在进行。
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3540933809);
}

/**
 * Start 解析 IP 文本并开始测速。已在测速时返回错误。
 */
export function Start(text: string): $CancellablePromise<void> {
    return $Call.ByID(1210520814, text);
}

/**
 * Stop 手动停止测速。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(171725110);
}
